lwip-wrapper/lwipopts.h, src/stream.zig
We're going to evaluate the performance.
The current max number of TCP connections is about 128. It's too low.
This PR increase it to 1024.
=> increase max number of tcp connections

src/fs.zig
This PR fixes the bug that it unintentionally break the file-search loop in `getFileByName`.
=> fix getFileByName not to break the loop

src/fs.zig
This PR fixes the bug that in `OpenedFile.read` it can overwrite the input buffer out of the range.
=> OpenedFile: handle case when reading file that is larger than input buffer

lwip-wrapper/tcpip.c, src/lwip.zig, src/stream.zig, src/tcpip.zig, src/uart.zig, src/wasi.zig
In lwIP's `tcp_write()` function, it can't send data larger than `pcb->snd_buf`. If it try to do it, it returns `ERR_MEM`.
This PR fixes `Socket.send` function not to send data larger than `pcb->snd_buf`. If it is requested to do that, it only sends the first `pcb->snd_buf` bytes data.
=> fix Socket.send not to try to send larger data than it actually can send

src/wasi/types.zig
We should use `extern struct` for structs defined by wasi-libc.
[extern struct](https://ziglang.org/documentation/master/#extern-struct) has in-memory layout matching the C ABI for the target
But [packed struct](https://ziglang.org/documentation/master/#packed-struct) has no padding, which breaks the in-memory-layout of the C ABI.
=> wasi/types.zig: use extern struct instead of packed struct

scripts/build-fs.sh
Wasm applications only can access the relative path to the current directory. So the root directory should be `.`.
=> handle root directory as `.`

build.zig, scripts/build-fs.sh, src/fs.zig
The generated files while build-process should be in `build/`.
=> move disk.o and disk.tar to build/

src/drivers/virtio/common.zig
We should update `queue_select` to the index of the queue before notifying.
=> fix notifyQueue to update queue_select before notifying

src/poll.zig, src/stream.zig, src/tcpip.zig
`poll_one_off` should return an event which shows it can read/write 0 bytes from/to fd when the connection is closed.
If not so, file descriptors of closed connections are not closed because the application cannot know the connections are closed.
=> fix poll_one_off to return 0 bytes when the connection is closed

src/drivers/virtio/net.zig, src/lwip.zig
It should call `sys_checkout_timeouts` periodically for lwIP to manage timeouts.
=> add sys_checkout_timeouts

src/drivers/virtio/common.zig, src/drivers/virtio/net.zig
Suppressing the number of VMExit and interrrupts brings intensive performance improvement!
=> virtio net: interrupt coalescing

src/drivers/virtio/common.zig, src/drivers/virtio/net.zig, src/timer.zig
Like #37, this PR suppresses the number of VMExit when sending packets.
It also improves performance!
=> virtio net: interrupt coalescing when sending packets

src/boot.S
This patch fixes crash in KVM-enabled AMD CPU.
As for Intel CPU, the 8th bit in PML4E is ignored. But as for AMD CPU, the 8th bit in PML4E Must Be Zero. Setting 8th bit in PML4E on AMD CPU causes crash.
We must not set the 8th bit in PML4E and PDPTE.
Reference
- Intel® 64 and IA-32 Architectures Software Developer’s Manual Vol.3, Figure 4-11
- AMD64 Architecture Programmer’s Manual Vol.3, Figure 5-20
=> Not to set bit 8 in PML4E, PDPTE

src/mem.zig
This fixes page fault on AMD CPU.
This is a same problem in 99ed760.
=> Not to set global flag except level 1 entry (PTE)

src/mem.zig
Base address and length must be aligned to BLOCK_SIZE, but currently aligned to PAGE_SIZE.
This causes General Protection Exception in some cases.
This patch fixes wrong alignment.
=> align allocator's base address and length to BLOCK_SIZE

lwip-wrapper/tcpip.c, src/main.zig, src/tcpip.zig
The mac address is hard-coded now.
This PR fixes so that it sets the mac address as the value from virtio net.
=> lwip: set mac address from virtio net

.github/workflows/ci.yaml, README.md, build.zig, scripts/create-test-dir.sh, scripts/integration-test.sh
And now we can pass the integration tests by just doing `zig build -Dtest=true run`
=> CI: add integration test

build.zig, scripts/build-fs.sh, src/fs.zig, src/wasi.zig
To test the file system in the integration test, we need to attach a directory to the VM.
But `params.dir_path` is overwritten in the current implementation.
This PR fixes so that `params.dir_path` is correctly set as `TEST_DIR_PATH`.
=> integration test: attach a test directory to test file system

scripts/integration-test.sh
We cannot see the output of Mewz when running the integration test.
This PR fixes it by using tee.
=> integration test: show output of Mewz

src/wasi.zig
Please review this for me, thank you!，#59
=> Add a test for reading a file

src/wasi.zig
`base` is the offset of the memory region the test codes can use in Linear Memory Address. But the value is always 0. So we don't need to use this variable.
FYI: We needed `base` because it was not always 0 in the midst of the development.
=> integration test: delete base

.devcontainer/Dockerfile, .github/workflows/ci.yaml, build.zig, src/drivers/virtio/common.zig, src/fs.zig, src/sync.zig, src/timer.zig, src/x64.zig
ref: https://github.com/ziglang/zig/issues/18482
```
kernel.entry = .{ .symbol_name = "boot" };
```
=> upgrade zig to 0.12.1

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .gitignore, Dockerfile, build.zig, src/drivers/virtio/common.zig, src/fs.zig, src/main.zig, src/mem.zig, src/param.zig, src/pci.zig, src/rand.zig, src/x64.ld, src/x64.zig
- upgrade zig to `0.14.0-dev.2540+f857bf72e`
- fix build.zig to compatible with the version
- remove `@fence` because it's removed from Zig's builtin functions
- I believe it works without `@fence`...
- fix linker script to contain `.lbss`, `.ldata`, `.lrodata`
- fix initialization of memory to be compatible with Multiboot spec
=> upgrade zig to 0.14

.gitmodules
=> chore: fix lwip remote url
